//fuck every ddr song

//const { TwitterApi } = require('twitter-api-v2');
//const twitterClient = new TwitterApi('AAAAAAAAAAAAAAAAAAAAAOWJYgEAAAAAImfXRPtTojprmP3N%2ByM80xxEfrA%3DSWZz8Zj5l3OCx5RXlD76meSrnDz4aSp7HewsC7OqnC5VB2MJpG');
//const rwClient = twitterClient.readWrite;
//https://github.com/plhery/node-twitter-api-v2/blob/HEAD/doc/examples.md

var fs = require('fs');

//function returns a random number
var randomnumber = function(max) {
    return Math.floor(Math.random() * Math.floor(max));
  }
  
  function songName()
  {
      var songlist = [
        "trip machine",
        "paranoia",
        "jam jam raggae",
        "butterfly",
        "have you ever been mellow",
        "kung fu fighting",
        "let's get down",
        "little bitch",
        "my fire",
        "strictly business",
        "that's the way (i like it)",
        "bad girls",
        "boom boom dollar",
        "boys",
        "dub-i-dub",
        "el ritmo tropical",
        "get up'n move",
        "hero",
        "i believe in miracles",
        "if you were here",
        "love",
        "smoke",
        "stomp to my beat",
        "tubthumping",
        "am-3p",
        "brilliant 2u",
        "brilliant 2u (orchestra-groove)",
        "make it better (so-real mix)",
        "paranoia max ~dirty mix",
        "put your faith in me",
        "put your faith in me (jazzy groove",
        "sp-trip machine ~jungle mix~",
        "make a jam",
        "paranoia kcet ~clean mix~",
        "20, november",
        "keep on movin",
        "let them move",
        "boom boom dollar (k.o.g. g3 mix",
        "butterfly (upswing mix)",
        "captain jack (grandale mix)",
        "dam dariram",
        "do it all night",
        "flashdance (what a feeling)",
        "follow the sun ('90 in the shade mix)",
        "get up and dance",
        "holiday",
        "if you can say goodbye",
        "in the navy '99 (xxxl disaster remix)",
        "it only takes a minute (extended remix)",
        "mr. wonderful",
        "oh nick please not so quick",
        "operator",
        "rock beat",
        "so many men",
        "upside down",
        "vol. 4",
        "xanadu",
        "afronova",
        "dead end",
        "dynamite rave",
        "end of the century",
        "gentle stress (amd sexual mix)",
        "gradiusic cyber ~amd g5 mix~",
        "la senorita",
        "luv to me (amd mix)",
        "paranoia rebirth",
        "silent hill",
        "1,2,3,4,007",
        "boys (euro mix)",
        "dream a dream",
        "eat you up",
        "furuhata's theme",
        "have you ever been mellow",
        "hero (happy grandale mix)",
        "if you were here",
        "in the heat of the night",
        "kick the can",
        "music",
        "night in motion",
        "little bitch",
        "only you",
        "pink dinosaur",
        "saint goes marching (remix)",
        "shake your booty",
        "shooting star",
        "the 7 jump",
        "walkie talkie",
        "b4u",
        "baby baby gimme your love",
        "burnin' the floor",
        "higher",
        "hypnΦtic crisis",
        "love again tonight ~for melissa mix~",
        "my summer love",
        "orion.78 (ameuro-mix)",
        "trip machine climax",
        "can't stop fallin' in love",
        "drop out",
        "hysteria",
        "let the beat him 'em",
        "paranoia evolution",
        "super star",
        "wild rush",
        ".59",
        "era (nostalmix)",
        "leading cyber",
        "never let you down",
        "conga feeling",
        "lupin the 3rd '78",
        "na-na",
        "petit love",
        "rhythm and police (k.o.g. g3 mix)",
        "sky high",
        "syncronized love (red monster hyper mix)",
        "wonda (speed k mix)",
        "do me (h.i.g.e.o. mix)",
        "sexy planet",
        "abyss",
        "サナ・モレッテ・ネ・エンテ",
        "i was the one",
        "absolute",
        "the cube",
        "dxy",
        "radical faith",
        "remember you",
        "dancing all alone",
        "swing it",
        "test my best",
        "be together",
        "the twist (double pump mix)",
        "never ending story",
        "healing vision",
        "hot limit",
        "moonlight shadow",
        "my generation (fat beat mix)",
        "dive",
        "broken my heart",
        "祭 Japan",
        "ecstasy",
        "still in my heart",
        "can't stop falling in love (speed mix)",
        "insertion",
        "paranoia eternal",
        "somewhere over the rainbow",
        "highs off u (scorccio xy mix)",
        "www.blonde girl (momo mix)",
        "bye bye baby balloon",
        "cow girl",
        "ghosts (vincent de moor remix)",
        "miracle",
        "with doctor (giant toons version)",
        "do you remember me",
        "justify my love",
        "the centre of the heart (stonebridge clubmix)",
        "i'm in the mood for dancing",
        "nori nori nori",
        "let's groove",
        "そばかす freckles (kcp re-edit)",
        "flash in the night",
        "my sweet darlin",
        "so deep (perfect sphere remix)",
        "fantasy",
        "true... (radio edit)",
        "firefly",
        "exotic ethnic",
        "on the jazz",
        "do it right",
        "share my love",
        "look to the sky",
        "midnite blaze",
        "healing vision (angelic mix)",
        "groove 2001",
        "max 300",
        "kind lady",
        "a minute",
        "drifting away",
        "it's raining men",
        "long train runnin'",
        "maximum overdrive",
        "stay",
        "the reflex",
        "living in america",
        "more than i needed to know",
        "the whistle song",
        "there you'll be",
        "waka laka",
        "destiny",
        "ever snow",
        "secret redez-vous",
        "candy♥",
        "dive to the night",
        "tsugaru",
        "burning heat",
        "i feel",
        "spin the disc",
        "maxx unlimited",
        "革命",
        "burnin' the floor",
        "cartoon heroes (speedy mix)",
        "i do i do i do",
        "irresistiblement",
        "la copa de la vida",
        "senorita (speedy mix)",
        "speed over beethoven",
        "we will rock you",
        "1998",
        "321 stars",
        "a",
        "across the nightmare",
        "air",
        "bag",
        "crash!",
        "cutie chaser",
        "dance dance revolution",
        "feeling of love",
        "drop the bomb",
        "happy wedding",
        "gamelan de couple",
        "hyper eurobeat",
        "i'm gonna get you!",
        "janejana",
        "jet world",
        "kiss kiss kiss",
        "la bamba",
        "love♥shine",
        "memories",
        "paranoia survivor",
        "paranoia survivor max",
        "pink rose",
        "so in love",
        "stoic (extreme version)",
        "sync (extreme version)",
        "tears",
        "the legend of max",
        "trip machine survivor",
        "v (for extreme)",
        "vanity angel",
        "white lovers",
        "xenon",
        "大見解",
        "桜",
        "a love like this",
        "give me up",
        "golden sky",
        "jerk it out",
        "wookie wookie",
        "baby's tears",
        "flow",
        "flow (true style)",
        "honey♂punch",
        "innocence of silence",
        "peace(^^)v",
        "aa",
        "curus",
        "happy☆angel",
        "moon",
        "murmur twins",
        "quick master",
        "no. 13",
        "xepher",
        "red zone",
        "under the sky",
        "jam & marmalade",
        "logical dash",
        "love is orange",
        "peace-out",
        "healing-d-vision",
        "fascination maxx",
        "fascination -eternal love mix-",
        "chaos",
        "stealth",
        "waiting for tonight",
        "faint",
        "a thing called love",
        "electrified",
        "freeway shuffle",
        "music in the rhythm",
        "volcano",
        "saturn",
        "sunkiss♥drop",
        "raspberry♥heart (english version)",
        "arrabbiata",
        "mars war 3",
        "baby's tears",
        "trim",
        "moonster",
        "dead end (groove radar special)",
        "uranus",
        "happy",
        "koko soko",
        "a geisha's dream",
        "dance celebration",
        "dream machine",
        "dance floor",
        "how to play",
        "party nights",
        "slip out",
        "taj he spitz",
        "taj he spitz (tommie sunshine's brooklyn fire re-touch)",
        "take a chance",
        "malacca",
        "puzzle",
        "dazzle",
        "on the break",
        "saber wing",
        "saber wing (akira ishihara headshot mix)",
        "horatio",
        "on the bounce",
        "trigger"


      ];

      return songlist[randomnumber(songlist.length)]
  }


  function generatePost(){
    
        //determine song
        var effit = "fuck " + songName();
        //twitterClient.v1.tweet(effit);

        console.log(effit);
        return effit;
        
    }


  //generatePost();

//debug - run a whole buttload
setInterval(generatePost, 300);